name: 🐞 Bug report
description: Noticed something not working as expected?
title: ""
labels: ["type - bug report"]
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Description of the bug
    description: A short description of what the problem is.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Provide steps that reproduce the problem. Please be as detailed as possible.
    placeholder: |
      1. Go to ...
      2. Click on ...
      3. Scroll down to ...
  validations:
    required: false
- type: textarea
  attributes:
    label: Actual behavior
    description: Describe what was the result of following the steps above. Add screenshots if you think they would help.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected behavior
    description: Describe what you expected to happen instead. Add mockup screenshots if possible.
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional information
    description: |
      Add any other information that could help. Examples:
        - **Backdrop CMS version**: 1.20.3
        - **Web server and its version**: Apache 2.4.38
        - **Operating System and its version**: Debian
    value: |
      - Backdrop CMS version:
      - Web server and its version:
      - Operating System and its version:
      - Browser(s) and their versions:
  render: markdown
validations:
  required: false
