blank_issues_enabled: false
contact_links:
  - name: Backdrop Security Team
    url: security@backdropcms.org
    about: If you believe you may have discovered a security issue with Backdrop CMS, contact the Backdrop Security Team directly. In order to keep everyone safe, we manage security issues separately in a private repository. So please refrain from publicly blogging, or tweeting about it until the issue has been resolved.
